import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/navigation">Navigation</Link>
        </li>
        <li>
          <Link to="/hello">Hello</Link>
        </li>
        <li>
          <Link to="/cover">Cover</Link>
        </li>
        <li>
          <Link to="/typographymaintext">TypographyMaintext</Link>
        </li>
        <li>
          <Link to="/typographylist">TypographyList</Link>
        </li>
        <li>
          <Link to="/typographyquotationmainpoint">
            TypographyQuotationMainpoint
          </Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
